### ISSUE TITLE
Investigate missing widget Apex Launcher

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#94]
As reported, the widget does not show up on Apex launcher, even if it's loaded.

**Comment by rock3r** [comment]
Sometimes happens on the Google Experience Launcher as well. Usually fixed by reinstalling the app. Not sure if it's really a widget issue, there's no code in the widget for that. I'd double check if this is related to the crashes in Apex when scrolling through the widgets list (bitmap decoding issues, not sure if related to FWeather preview bitmap or other widget's).

**Comment by rock3r** [comment]
PS: have fun.

**Comment by frapontillo** [comment]
Can't reproduce.
